### ISSUE TITLE
high priority 

### ISSUE THREAD

**Issue by Aravindramayampet** [weibeld/terraform-aws-kubeadm#10]
I am getting the following error on my local machine as well as the ec2 master node:

 terraform-kubeadm % kubectl --kubeconfig admin.conf get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by weibeld** [comment]
This should most probably be resolved with the bug fix in [0.2.6](https://github.com/weibeld/terraform-aws-kubeadm/releases/tag/0.2.6).
