### ISSUE TITLE
kubelet issue

### ISSUE THREAD

**Issue by Omar-El** [weibeld/terraform-aws-kubeadm#3]
is it normal that after restarting the kubelet, the node becomes not ready ?

**Comment by weibeld** [comment]
It should eventually become ready again. You can find out the reason why it's not ready with:

```bash
kubectl describe node <node-name>
```

**Comment by Omar-El** [comment]
I don't think so, the state is still not ready, and the kubectl describe node doesn't give any clarification
now every pod has a pending status.
![state](https://user-images.githubusercontent.com/37773673/86384116-4192ca00-bc86-11ea-9306-9f000db8c1ea.PNG)
![master](https://user-images.githubusercontent.com/37773673/86384160-45265100-bc86-11ea-9dde-04424dce89bd.PNG)
![worker](https://user-images.githubusercontent.com/37773673/86384172-46f01480-bc86-11ea-8d68-3a843523489f.PNG)

**Comment by peteroneilljr** [comment]
@Omar-El I had this same problem. The cluster doesn't have a CNI be default so the nodes won't ever become ready. Once you add Calico or Flannal it should start to work.
